apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000

  selector:
    component: backend
    app: myplastyka-app
