apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  labels:
    component: frontend
    app: myplastyka-app

spec:
  template:
    metadata:
      name: frontend-pod
      labels:
        component: frontend
        app: myplastyka-app
    spec:
      containers:
        - name: frontend-container
          image: zofiat/frontend-myplastyka-app:latest

  replicas: 1
  selector:
    matchLabels:
      app: myplastyka-app
      component: frontend
