apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres-deployment
  labels:
    component: postgres
    app: myplastyka-app
    type: db

spec:
  template:
    metadata:
      name: postgres-pod
      labels:
        component: postgres
        app: myplastyka-app
        type: db
    spec:
      containers:
        - name: postgres-container
          image: postgres:alpine
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresvolume
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: myplastyka-app-secret
                  key: PGPASSWORD

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: myplastyka-app-config
                  key: PGDATABASE

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: myplastyka-app-config
                  key: PGUSER

      volumes:
        - name: postgresvolume
          persistentVolumeClaim:
            claimName: postgres-pvc
  
  replicas: 1
  selector:
    matchLabels:
      app: myplastyka-app
      type: db
