apiVersion: v1
kind: Pod
metadata: 
  name: my-redis-pod
  labels: 
    component: web
    app: my-app

spec:
  containers:
    - name: my-redis
      image: redis:alpine
      ports:
        - containerPort: 80