apiVersion: v1
kind: Service
metadata:
  name: my-backend-node-port

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31100

  selector:
    component: web-backend
    app: my-app
