apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-nginx-deployment
  labels:
    component: web-frontend
    app: my-app

spec:
  template:
    metadata:
      name: my-nginx-pod
      labels:
        component: web-frontend
        app: my-app
    spec:
      containers:
        - name: my-nginx-container
          image: zofiat/my-web-frontend-nginx:latest
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      component: web-frontend
